POST http://localhost:7071/api/orchestrators/Simulation HTTP/1.1

####
POST http://localhost:7071/api/orchestrators/hello_orchestrator HTTP/1.1

####
POST http://localhost:7071/api/simulations/1234-5678/stop HTTP/1.1

####
POST http://localhost:7071/runtime/webhooks/durabletask/instances/1234-5678/terminate

####
GET https://simulation-app.delightfultree-1857026e.westus.azurecontainerapps.io/simulations HTTP/1.1

####
POST http://localhost:7071/api/SimulationLoopWebhook HTTP/1.1
Content-Type: application/json

{
"id": "12345",
"subject": "/subscriptions/example-subscription/resourceGroups/example-resource-group",
"data": {
    "message": "This is sample event data 2",
    "priority": "high",
    "status": "completed"
},
"eventType": "Example.Event",
"eventTime": "2023-10-15T18:30:00Z",
"dataVersion": "1.0",
"metadataVersion": "1",
"topic": "/subscriptions/example-subscription/resourceGroups/example-resource-group/providers/Microsoft.EventGrid/topics/example-topic"
}

####
