POST http://localhost:7071/api/simulations/1234-5678/start HTTP/1.1

####
POST http://localhost:7071/api/simulation_loop_webhook HTTP/1.1
Content-Type: application/cloudevents+json

{
    "specversion": "1.0",
    "type": "Example.Event",
    "source": "/subscriptions/example-subscription/resourceGroups/example-resource-group",
    "id": "12345",
    "time": "2023-10-15T18:37:00Z",
    "datacontenttype": "application/json",
    "subject": "sensor1",
    "data": {
        "message": "This is sample event data 4"
    }
}

####
POST http://localhost:7071/api/simulations/1234-5678/stop HTTP/1.1


####
POST http://localhost:7071/runtime/webhooks/durabletask/instances/1234-5678/terminate

